### PR TITLE
Fix code validation layer enabled on release configuration

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes https://github.com/ppy/osu-framework/issues/5893

### CODE REVIEW

**Comment by peppy** [comment]
@smoogipoo curious on your thoughts here.

We are basically always using a release build of veldrid, so this will remove the checks for our usage. But have they ever benefitted us? If not, it might be something we want to keep off on the fork just to reduce overheads.

BUT, the major cause of concern was the overhead from this on iOS, which as we've since discovered is due to interpreter mode.

**Comment by smoogipoo** [comment]
Hmm... The validation checks don't look _super_ expensive, but they do a lot of what should be quick work. @frenzibyte can tell more if the validation has helped, because much of `VeldridRenderer` is his implementation.

Though I'll say that some renderers have very non-descript error messages - D3D for one seems to be all about giving you the least possible debugging info, for some reason.

**Comment by frenzibyte** [comment]
Hmm yeah, I did encounter a lot of cases where validation helped, I'll retest this later with AOT and see if there's really any benefit.

**Comment by peppy** [comment]
Shall we close this?

**Comment by frenzibyte** [comment]
Yup, https://github.com/ppy/osu-framework/issues/5893#issuecomment-1624481415.

**Pull request closed without merging**
